config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :servers
  resources :users
  resources :user_sessions, only: [:create, :new, :destroy]

  root 'user_sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/login.rb
class Login < ApplicationRecord
  belongs_to :user
  belongs_to :server
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :create, :show, :edit, :update, :destroy]


  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
    @servers = Server.all
    @login.user_id = params[:id]
  end

  # GET /logins/1/edit
  def edit
    @servers = Server.all
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:login, :senha, :user_id, :server_id)
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :login_login %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :login_senha %>
  </div>

  <div class="field">
    <%= form.label current_user.nome %>
    <%= form.text_field :user_id, id: :login_user_id %>
  </div>

  <div class="field">
    <%= form.label :servers %>
    <%= form.select :server_id, @servers.collect  {|s| [ s.nome, s.id ] }, prompt: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1 style="text-align: center;font-size:40px"> Login Servidor</h1>
<div style="background-color: #483D8B;height: 10px"></div>

<div class="row">
<div class="col-lg-10" style="margin-left: auto;margin-right: auto;">
<br><div><%= link_to 'New Login', new_login_path, class: 'btn btn-primary' %></div>
<p id="notice"><%= notice %></p>



<table class="table table-hover" style="margin-top: 50px">
  <thead>
    <tr>
      <th colspan="1">Login</th>
      <th colspan="1">Senha</th>
      <th colspan="1">User</th>
      <th colspan="1">Server</th>
      <th colspan="3"></th>
    </tr>
    </thead>
  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.login %></td>
        <td><%= login.senha %></td>
        <td><%= login.user.nome %></td>
        <td><%= login.server.nome %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody> 
</table>
</div>
</div>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @login.login %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @login.senha %>
</p>

<p>
  <strong>User:</strong>
  <%= @login.user.nome %>
</p>

<p>
  <strong>Server:</strong>
  <%= @login.server.nome %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>