config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :servers
  resources :users
  resources :user_sessions, only: [:create, :new, :destroy]

  root 'user_sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/server.rb
class Server < ApplicationRecord
	validates_presence_of :nome, :url
	has_many :login
	has_many :users, through: :login
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy, :show]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:nome, :url)
    end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_with(model: server, local: true) do |form| %>
  <% if server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :server_nome %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :server_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<p id="notice"><%= notice %></p>
<div style="background-color: #483D8B;height: 10px"></div>
<div>
  <h1 style="font-family: verdana;text-align: center;margin-top: 20px;"><b>Servers</b></h1>
  <p style="margin-left: 50px;"><%= link_to 'New Server', new_server_path %></p>
</div>

<table class="table table-hover" style="margin-top: 50px">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Url</th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.nome %></td>
        <td><%= server.url %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form', server: @server %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Nome:</strong>
  <%= @server.nome %>
</p>

<p>
  <strong>Url:</strong>
  <%= @server.url %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>