config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :servers
  resources :users
  resources :user_sessions, only: [:create, :new, :destroy]

  root 'user_sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates_presence_of :nome, :password, :password_confirmation
	has_many :login
	has_many :servers, through: :login, source: :user

	def self.authenticate(nome, password)
      find_by(nome: nome).
      try(:authenticate, password)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :can_change, only: [:edit, :update]
  before_action :require_authentication, only: [:edit, :update, :destroy, :show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_login_path(id: @user.id), notice: 'User was successfully created.'}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :password, :password_confirmation)
    end

    def can_change
      unless user_signed_in? && current_user == user
        redirect_to user_path(params[:id])
      end
    end
  
  def user
    @user ||= User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :user_nome %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div style="background-color: #483D8B;height: 10px"></div>

<div>
  <h1 style="font-family: verdana;text-align: center;margin-top: 20px;"><b>Users</b></h1>
  <p style="margin-left: 50px;"><%= link_to 'New User', new_user_path %></p>
</div>

<table class="table table-hover" style="margin-top: 50px">
  <thead>
    <tr>
      <th colspan="2">Nome</th>
      <th colspan="2"></th>
    </tr>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nome %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>

  </thead>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<br><h1 style="text-align: center;">Perfil</h1>
<div style="background-color: #483D8B;height: 10px"></div>

<div class="row" style="margin-top: 50px">
<div class="col-lg-10" style="margin-left: auto;margin-right: auto;">
<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
	<%= link_to 'Associar login de servidor', new_login_path(id: current_user), class: "btn btn-large btn-primary" %>
</p>



<table class="table table-hover" style="margin-top: 50px">
  <thead>
    <tr>
      <th colspan="1">Servidor</th>
      <th colspan="1">Login</th>
      <th colspan="1">Senha</th>
      <th colspan="1"></th>
      <th colspan="1"></th>
    </tr>
  <tbody>
    <% @user.login.each do |login| %>
      <tr>
        <td><%= login.server.nome %></td>
        <td><%= login.login %></td>
        <td><%= login.senha %></td>
        <td><%= link_to 'Fazer Login', login.server.url+'?nome='+login.login+'&password='+login.senha, target: "_blank", rel: "nofollow" %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
      </tr>
    <% end %>
  </tbody>

  </thead>
</table>
<%= link_to 'Edit', edit_user_path(@user) %> |

<%= link_to 'Back', users_path %>
</div>
</div>